package com.github.hotire.webservice.feign.config;

import org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider;

public class CustomClassPathScanningCandidateComponentProvider extends ClassPathScanningCandidateComponentProvider {
}
